### ISSUE TITLE
Compile error with v1.5.0

### ISSUE THREAD

**Issue by matthias-bs** [theengs/decoder#363]
**Describe the bug**
/home/runner/Arduino/libraries/TheengsDecoder/src/decoder_c.cpp:26:10: fatal error: shared/theengs.h: No such file or directory
 #include "shared/theengs.h"

**To Reproduce**
see https://github.com/matthias-bs/BresserWeatherSensorTTN/blob/test-theengsdecoder-v1.5.0/.github/workflows/CI.yml
The CI workflow works fine with v1.4.2 and fails with v1.5.0
Same error occurs when compiling with Arduino IDE v2.1.0 / ESP32 Arduino 2.07

**Expected behavior**
No compile error

**Screenshots**

**Environment (please complete the following information):**
* version used (V0.9.3, 0.8, development)
* Context of your project

**Additional context**

* You should not have a compilation error if you use the versions of the libraries linked into the libraries folder, this badges show you the state of the compilation 
[![Build Status](https://github.com/theengs/decoder/workflows/Build/badge.svg?branch=development)](https://github.com/theengs/decoder/actions)
* If you are not sure this is a bug or an enhancement post your question to the forum

**Comment by DigiH** [comment]
@kabili207 can you have a look what is happening here?

**Comment by matthias-bs** [comment]
Release v1.5.1 was provided by the Arduino Library Manager and could be used in CI, which solved the problem. But strange enough, I cannot see v1.5.1 in the releases.

**Comment by DigiH** [comment]
@matthias-bs 1.5.1 was a test build erroneously getting into the wild for a very shorts time.

A new Decoder release is upcoming.

**Comment by DigiH** [comment]
Hi @matthias-bs

The compile error should be gone with the Theengs Decoder 1.5.5 release.

Please close the issue if you can verify a correct build.

Thanks

**Comment by matthias-bs** [comment]
Thank you for the quick solution!
